theme: jekyll-theme-slate
title: Dynamic Asset Code Repository
description: Solves infinite-horizon exogenously-incomplete dynamic programming asset problems in discrete-time. Household-side problem of the Bewley Aiyagari type heterogeneous agent model. Models with savings, borrowing (default), safe and risky asset choices, and formal and informal choices.
google_analytics: UA-92953468-5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
