theme: jekyll-theme-slate
title: Dynamic Asset Code Repository
description: Solving Heterogenous Agents Dynamic Asset Models
google_analytics: UA-92953468-5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
